title: FrachilizGamer Blog
author: frachilizgamer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 primeramete bienvenidos a mi primer blog totalmente hecho por mi donde habran temas de conversacion exelentes por escuchar y aprender

# social links
twitter_username: frachiliz # DO NOT include the @ character, or else the build will fail!
github_username:  frachilizgamer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
